import { Bounty, Group, IOU, User } from './models';

const now = new Date();
const days = (n: number) => new Date(now.getTime() + n * 86400000);
const hours = (n: number) => new Date(now.getTime() + n * 3600000);

export const MOCK_USERS: User[] = [
  { uid: 'u-ria',  displayName: 'Ria M.',   handle: 'ria',  initials: 'RM', avatarVariant: 3, totalPoints: 285 },
  { uid: 'u-nora', displayName: 'Nora K.',  handle: 'nora', initials: 'NK', avatarVariant: 2, totalPoints: 220 },
  { uid: 'u-dan',  displayName: 'Dan J.',   handle: 'dan',  initials: 'DJ', avatarVariant: 4, totalPoints: 175 },
  { uid: 'u-sam',  displayName: 'Sam M.',   handle: 'sam',  initials: 'SM', avatarVariant: 5, totalPoints: 110 },
  { uid: 'u-jess', displayName: 'Jess L.',  handle: 'jess', initials: 'JL', avatarVariant: 1, totalPoints: 95  },
  { uid: 'u-eli',  displayName: 'Eli P.',   handle: 'eli',  initials: 'EP', avatarVariant: 2, totalPoints: -30 },
  { uid: 'u-theo', displayName: 'Theo G.',  handle: 'theo', initials: 'TG', avatarVariant: 4, totalPoints: -45 },
];

export const CURRENT_USER_ID = 'u-ria';

export const MOCK_GROUPS: Group[] = [
  {
    id: 'g-office',
    name: 'Office shenanigans',
    emoji: '💼',
    ownerId: 'u-ria',
    inviteCode: 'OFC-X7K',
    memberIds: MOCK_USERS.map((u) => u.uid),
    defaultExpiryDays: 7,
    unreadCount: 7,
    surfaceTone: 'info',
  },
  {
    id: 'g-pub',
    name: 'The Pub Quiz',
    emoji: '🍻',
    ownerId: 'u-nora',
    inviteCode: 'PUB-22B',
    memberIds: ['u-ria','u-nora','u-dan','u-sam','u-jess','u-eli','u-theo'],
    defaultExpiryDays: 5,
    unreadCount: 5,
    surfaceTone: 'primary',
  },
  {
    id: 'g-ski',
    name: 'Ski trip 2026',
    emoji: '🏔️',
    ownerId: 'u-dan',
    inviteCode: 'SKI-99M',
    memberIds: ['u-ria','u-nora','u-dan','u-sam','u-jess','u-theo'],
    defaultExpiryDays: 14,
    unreadCount: 0,
    surfaceTone: 'success',
  },
];

export const MOCK_BOUNTIES: Bounty[] = [
  {
    id: 'b-9k2',
    groupId: 'g-office',
    title: 'Hide in the 3rd floor bathroom for the full 9:30 standup.',
    description: 'Stall #2 is the canonical one. Proof = standup attendance roster screenshot showing you absent.',
    price: 30,
    state: 'available',
    posterId: 'u-nora',
    claimantId: null,
    expiresAt: days(5),
    createdAt: hours(-2),
  },
  {
    id: 'b-tie',
    groupId: 'g-office',
    title: 'Wear a tie to every meeting this week. Photo proof daily.',
    description: 'Five days, five ties. No repeats. Group chat verifies daily.',
    price: 50,
    state: 'claimed',
    posterId: 'u-dan',
    claimantId: CURRENT_USER_ID,
    expiresAt: days(4),
    createdAt: hours(-26),
  },
  {
    id: 'b-slack',
    groupId: 'g-office',
    title: 'Send an "all in favor" Slack vote about adding a ping-pong table.',
    description: 'Must be in #general, must use the slash command, must tag the CEO.',
    price: 15,
    state: 'pending_review',
    posterId: CURRENT_USER_ID,
    claimantId: 'u-sam',
    proof: { urls: ['slack-screenshot.png'], note: '"Got 11 reacts in the channel and HR has questions. We winning?"' },
    expiresAt: days(2),
    createdAt: hours(-3),
  },
  {
    id: 'b-ceo',
    groupId: 'g-office',
    title: 'Call the CEO by their first name in the all-hands.',
    description: 'Live or it didn\'t happen. Recording counts.',
    price: 25,
    state: 'successful',
    posterId: 'u-nora',
    claimantId: CURRENT_USER_ID,
    expiresAt: days(-1),
    createdAt: days(-3),
    resolvedAt: days(-1),
  },
  {
    id: 'b-haiku',
    groupId: 'g-office',
    title: 'Reply to every email in haiku form for one workday.',
    description: '5/7/5. Must include the word "synergy" at least once.',
    price: 10,
    state: 'available',
    posterId: 'u-sam',
    claimantId: null,
    expiresAt: days(2),
    createdAt: hours(-4),
  },
  {
    id: 'b-synergy',
    groupId: 'g-office',
    title: 'Use the word "synergy" 10× in standup.',
    description: 'Recording or transcript required. Bonus pts if anyone calls it out.',
    price: 20,
    state: 'pending_review',
    posterId: CURRENT_USER_ID,
    claimantId: 'u-dan',
    proof: { urls: ['standup-recording.mp4'], note: 'Hit 12 before Mark cut me off. Counts as a personal record.' },
    expiresAt: days(1),
    createdAt: hours(-6),
  },
  {
    id: 'b-pint',
    groupId: 'g-pub',
    title: 'Down a pint in under 8 seconds.',
    description: 'Lager only. Video must be one continuous take with a stopwatch in frame.',
    price: 40,
    state: 'pending_review',
    posterId: CURRENT_USER_ID,
    claimantId: 'u-nora',
    proof: { urls: ['pint-video.mp4'], note: '7.4s by the timer. Witness: Sam, Dan.' },
    expiresAt: days(1),
    createdAt: days(-1),
  },
  {
    id: 'b-coffee',
    groupId: 'g-office',
    title: 'Drink a coffee with no hands.',
    description: 'Full mug, no straw, no spillage. Group voted before claiming counts.',
    price: 10,
    state: 'failed',
    posterId: 'u-dan',
    claimantId: CURRENT_USER_ID,
    expiresAt: days(-2),
    createdAt: days(-4),
    resolvedAt: days(-2),
    rejectionReason: 'Visible hand contact at 0:14.',
  },
];

export const MOCK_IOUS: IOU[] = [
  {
    id: 'iou-1',
    groupId: 'g-office',
    debtorId: 'u-nora',
    creditorId: CURRENT_USER_ID,
    amount: 30,
    bountyId: 'b-ceo',
    status: 'open',
    createdAt: days(-1),
  },
  {
    id: 'iou-2',
    groupId: 'g-office',
    debtorId: CURRENT_USER_ID,
    creditorId: 'u-dan',
    amount: 45,
    bountyId: 'b-coffee',
    status: 'open',
    createdAt: days(-2),
  },
];
